
include: "rules/0_common.smk"
include: "rules/1_align_reads.smk"
include: "rules/2_call_vars.smk"
include: "rules/2_liftover.smk"


outputs = [
    rules.read_align_all.input,
    rules.call_vars_all.input,
    rules.liftover_all.input,
]

if config.get("annot"):

    include: "rules/2_annotate_ampl.smk"

    outputs.append(
        rules.annote_ampl_all.input,
    )


rule all:
    input:
        outputs,
