[workspace]
channels = ["conda-forge", "https://conda.anaconda.org/bioconda"]
name = "sperm_breakpoint"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake = { version = ">=9.26.1,<10", channel = "bioconda" }
snakefmt = { version = ">=2.0.3,<3", channel = "bioconda" }
snakemake-executor-plugin-slurm = ">=2.8.0,<3"
conda = "*"
ruff = "*"
samtools = { version = ">=1.24,<2", channel = "bioconda" }
