rerun-incomplete: True
show-failed-logs: True
rerun-triggers: mtime
restart-times: 0
software-deployment-method:
- conda
show-failed-logs: True
executor: slurm
jobs: 100
latency-wait: 60
max-jobs-per-second: 50
default-resources:
- mem=8G
- runtime=300
- slurm_account=owner-guest
- slurm_partition=kingspeak-guest
- slurm_qos=kingspeak-guest
