rerun-incomplete: True
show-failed-logs: True
rerun-triggers: mtime
restart-times: 0
software-deployment-method:
- conda
- apptainer
show-failed-logs: True
executor: slurm
jobs: 100
latency-wait: 60
max-jobs-per-second: 50
default-resources:
- mem=8G
- runtime=480
- slurm_account=owner-guest
- slurm_partition=kingspeak-guest
- slurm_qos=kingspeak-guest
# - slurm_account=elde-np
# - slurm_partition=elde-np
singularity-args: "-B /scratch,/usr/lib/locale/:/usr/lib/locale/"
