samples:
  - name: CT22
    asm_fa: data/PrimateTestisData/asm/GCA_965153165.1.fa.gz
    reads: [
      data/PrimateTestisData/reads/ERR14376368.bam
    ]

output_dir: "results"
logs_dir: "logs"
benchmarks_dir: "benchmarks"

# Align reads to DSA
align:
  # See https://github.com/logsdon-lab/Snakemake-Aligner
  threads_aln: 8
  mem_aln: 80G
  aligner: "minimap2"
  # See preset options
  # https://lh3.github.io/minimap2/minimap2.html
  aligner_opts: "--eqx -ax map-hifi -I 8G"
  # Omit unmapped reads. This is the inverse flag -F of samtools view.
  # This param could probably be named better
  # See here for flags
  # https://broadinstitute.github.io/picard/explain-flags.html
  samtools_view_flag: 4
  # Don't delete merged assembly.
  temp_asm: False

call_variants:
  threads_deepvariant: 32
  mem_deepvariant: 100G
  threads_pbsv: 8
  mem_pbsv: 40G
  threads_hiphase: 8
  mem_hiphase: 40G

# # Annotate repeats (RepeatMasker) and SDs (biser)
# annot:
#   threads_rm: 2
#   mem_rm: 8G
#   # RepeatMasker species
#   engine_rm: rmblast
#   species_rm: primates
#   # biser settings
#   threads_biser: 4
#   mem_biser: 300G

liftover:
  # Used for liftover bed and SafFire
  # Different params used for lifton and genes
  threads_aln: 8
  mem_aln: 120G
  # Minimap2 params
  # * -x asm20 for more divergent species
  # * --secondary=no for no secondary alignments
  # * -s for minimum alignment score
  # * -K for diploid assembly index size
  mm2_opts: "-x asm20 --secondary=no -s 25000 -K 8G"
  reference: 
    path: data/PrimateTestisData/asm/mPanTro3.analysis-dip.20231122.fasta.gz
    name: mPanTro3
  # Different annnotation types (bed or gff)
  # If gff, uses lifton
  annot:
    genes:
      path: /scratch/ucgd/lustre-labs/vollger/users/Keith/EldeLabRotation/data/annot/human/chm13v2.0_RefSeq_Liftoff_v5.3.gff
    sd:
      path: /scratch/ucgd/lustre-labs/vollger/users/Keith/EldeLabRotation/data/annot/human/segDups_2024.bed
      liftover_args: -bedPlus=9 # -multiple
