samples:
  - name: CT15
    asm_fa: data/PrimateTestisData/asm/GCA_965153145.1.fa.gz
    reads: [
      data/PrimateTestisData/reads/ERR14376286.bam
    ]
  - name: CT22
    asm_fa: data/PrimateTestisData/asm/GCA_965153165.1.fa.gz
    reads: [
      data/PrimateTestisData/reads/ERR14376368.bam
    ]
  - name: CT28
    asm_fa: data/PrimateTestisData/asm/GCA_965153115.1.fa.gz
    reads: [
      data/PrimateTestisData/reads/ERR14376446.bam
    ]
  - name: CT32
    asm_fa: data/PrimateTestisData/asm/GCA_965153035.1.fa.gz
    reads: [
      data/PrimateTestisData/reads/ERR14368733.bam
    ]

# Align reads to DSA
align:
  # See https://github.com/logsdon-lab/Snakemake-Aligner
  output_dir: "results/align"
  logs_dir: "logs/align"
  benchmarks_dir: "benchmarks/align"
  threads_aln: 12
  mem_aln: 70G
  aligner: "minimap2"
  # See preset options
  # https://lh3.github.io/minimap2/minimap2.html
  aligner_opts: "--eqx -ax map-hifi -I 8G"
  # Omit unmapped reads. This is the inverse flag -F of samtools view.
  # This param could probably be named better
  # See here for flags
  # https://broadinstitute.github.io/picard/explain-flags.html
  samtools_view_flag: 4
  # Don't delete merged assembly.
  temp_asm: False

# Annotate repeats (RepeatMasker) and SDs (biser)
annot:
  output_dir: "results/annot"
  logs_dir: "logs/annot"
  benchmarks_dir: "benchmarks/annot"
  threads_annot: 8
  mem_annot: 30G
  # RepeatMasker species
  repeatmasker_engine: rmblast
  repeatmasker_species: primates
